version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
