services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expressI0n
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/postgresql/pg_hba.conf:/etc/postgresql/common/pg_hba.conf

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pg.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data:
  pgadmin_data:
