CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(15) NOT NULL,
  last_name VARCHAR(15) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  login VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  age VARCHAR(10) NOT NULL,
  gender VARCHAR(10) NOT NULL
);
